
While the API can handle some simple and unequivocal cases of labels, it is recommended to create an instance of [.codecls]##QLabel##, provided by ``estampes.base.qlabel``.
The created instance (referred to in the following as _qlabel_, quantity label), provides a full characterization through its attributes.

[IMPORTANT]
====
The _qlabel_ instances are built with a protection mechanism.
It is not possible to modify a field once it is set, developers must reset all _qlabel_ fields before setting.
This design was intended to avoid a _qlabel_ being modified after data have been created, causing potential inconsistencies in some code logic (note however that the _qdata_ object contains a copy of the _qlabel_ used to generate the data).
====


== Interface

=== Constructor

The constructor of the [.codecls]##QLabel## class supports 2 specifications system:

* Full label characterization, in the format:
+
--
[subs="macros,attributes,quotes"]
----
[.codevar]##id_label##+[:[+[.codevar]##subopt##+][:[+[.codevar]##ord##+][:[+[.codevar]##coord##+][:[+[.codevar]##state(s)##+][:[+[.codevar]##level##+]]]]]]+
----

[horizontal]
[.codevar]##id_label##::
    quantity identifier as an integer or a string (see below for some examples).
[.codevar]##subopt##::
    sub-option (e.g., gauge, specific components)
[.codevar]##ord##::
    derivative order
[.codevar]##coord##::
    reference coordinates (derivatives)
[.codevar]##state(s)##::
    reference electronic state or transition (as `i->j`)
[.codevar]##level##::
    theoretical level: vibrational (harmonic/anharmonic), electronic...
--
* Through specific fields, that must be specified:

[horizontal]
[.codepar]##quantity##::
    quantity identifier (see below) or textual label
[.codepar]##descriptor##::
    sub-option (e.g., gauge, specific components)
[.codepar]##derorder##::
    derivative order
[.codepar]##dercoord##::
    reference coordinates (derivatives)
[.codepar]##refstate##::
    reference electronic state or transition (as [.codestr]##"i->j"##)
[.codepar]##level##::
    theoretical level: vibrational (harmonic/anharmonic), electronic...

=== Attributes

``[.codecls]##QLabel##.[.codekey]##qlabel##``::
    (*_integer_* or *_string_*)
    The main quantity label or identifier, which specifies what quantity is of interest.

``[.codecls]##QLabel##.[.codekey]##kind##``::
    (*_string_*, can be [.codelit]##None##)
    A sub-category, to refine the quantity specification.
    Possible values can be:

    * a variant specification if the quantity can be computed in different ways, for instance velocity or length gauge.
    * a sub-field if ``[.codecls]##QLabel##.[.codekey]##qlabel##`` refers to a generic category, for instance Franck--Condon calculations.
    * a specification if the quantity can be computed for different conditions, such as the incident frequency for Raman spectroscopy.

``[.codecls]##QLabel##.[.codekey]##derord##``::
    (*_integer_* or [.codelit]##None##)
    Derivative order, where relevant.
    `0` specifies the reference quantity.

``[.codecls]##QLabel##.[.codekey]##dercrd##``::
    (*_string_* or [.codelit]##None##)
    Reference coordinates system used for the derivation, where relevant.

``[.codecls]##QLabel##.[.codekey]##refstate##``::
    (*_string_*, *_tuple_*, *_integer_*, [.codelit]##None##)
    The reference electronic state for which the property/quantity was computed, where relevant. +
    Possible values are:
+
[horizontal]
    *_integer_*:::
        Electronic state number.
        `0` for ground state, `>0` for excited states.
        Mostly relevant to choose the correct electronic state in methods considering several electronic states.
        Can also be used to exclude data if not done for the state of interest.
    [.codestr]##"c"##:::
        (current) Wildcard to indicate the reference state of the calculation used to generate the data file to be parsed.
        No checks are applied.
    [.codestr]##"a"##:::
        (all) Extract data for all states present in the data file
    *_tuple_*:::
        Electronic transition moment, as ``(initial, final)``.
        The _final_ state can be [.codestr]##"a"## to specify all excited electronic states.
        Transition from the ground state to the first excited electronic state would be noted "```(0, 1)```"

``[.codecls]##QLabel##.[.codekey]##level##``::
    (*_string_*, can be [.codelit]##None##)
    Level of calculation used to compute the quantity.
    Possible values are:
+
[horizontal]
    [.codestr]##"E"##:::
        Electronic structure calculation, the quantity is purely electronic.
    [.codestr]##"VE"##:::
        Vibrationally-resolved electronic structure calculation, the quantity contains vibrational information computed on top of the electronic solution.
    [.codestr]##"H"##:::
        Vibrational level, within the harmonic-oscillator approximation.
    [.codestr]##"A"##:::
        Vibrational level, including anharmonic effects.




=== Methods

``[.codecls]##QLabel##.[.codefun]##build_qstring##()``::
    Returns the _qlabel_ as a *_string_*, using the old format.
    This is primarily used for backward-compatibility controls or to generate user-readable field names for arrays of _quantity data_ objects.

``[.codecls]##QLabel##.[.codefun]##reset##()``::
    Reset fields of _qlabel_.

``[.codecls]##QLabel##.[.codefun]##set##(*, [.codepar]##quantity##=[.codelit]##None##, [.codepar]##descriptor##=[.codelit]##None##, [.codepar]##derorder##=[.codelit]##None##, [.codepar]##dercoord##=[.codelit]##None##, [.codepar]##refstate##=[.codelit]##None##, [.codepar]##level##=[.codelit]##None##)``::
    Sets specific field(s).
+
--
[CAUTION]
====
The fields can only be set if they are unset ([.codelit]##None##).
Otherwise, the _qlabel_ can be first reinitialized.
====
--


== List of supported field values

The class is built to support in theory any quantity.
Support for some types of quantity have already been planned and formalized.

They are listed below:

include::dfmt_qlabel_fields.adoc[leveloffset=+1]
