= ESTAMPES: Data format of the API
:email: julien.bloino@sns.it
:revnumber: 0.6.0
:revremark: Bump to new version
:toc: left
:toclevels: 3
:icons: font
:stem:
:pygments-style: native

:Estampes: pass:q[[.smallcaps]##Estampes##]

== Preamble

{Estampes} provides an internal data structure to facilitate the handling of data, which may come from different sources.

There are 2 data structures used to communicate with the `DataFile` object provided by the internal parser:

* In input, to choose the data to extract, the *quantity label* (_qlabel_).
* In output, the extracted data, as dictionary (see below).

[WARNING]
.Compatibility breakup
====
Starting with version 0.5, the format of the _quantity labels_ and _extracted data_ has changed and are now handled through dedicated objects, respectively *_QLabel_* and *_QData_*.
The old style is deprecated---but remains supported in some cases--- and its use is discouraged, so the present documentation only considers the new format.

The change is particularly critical for the _quantity data_ objects generated by the parsers, since scripts using the old system will likely be broken.
====

== Input: the _quantity label_ object

include::api/dfmt_qlabel.adoc[leveloffset=+1]


== Output: the _quantity data_ object

include::api/dfmt_qdata.adoc[leveloffset=+1]
