= Ballast: A simple builder to display multiple spectra.
:email: julien.bloino@sns.it
:revnumber: 0.4.0
:revremark: Keyword for figure size proportional to number of rows/columns.
:toc: left
:toclevels: 1
:icons: font
:stem:

:Gaussian: pass:q[G[small]##AUSSIAN##]
:Estampes: pass:q[E[small]##STAMPES##]
:ESParser: pass:q[ESP[small]##ARSER##]
:Ballast: pass:q[B[small]##ALLAST##]

== Preamble

{Ballast} helps construct figures involving multiple spectra.


== Overview


== Requirements

* This script depends heavily on *Matplotlib* for the display of the spectra.


== Usage


== Command-line arguments


== Option file

An INI file can be given in place of arguments.
Its structure is divided in 2 blocks:

`figure`::
    Figure parameters.
`layout`::
    Layout of the spectrum. +
+
NOTE: For multiple sub-plots, the keyword layout can be followed by "`:`" and either a "`row,column`" or "`subplot_id`" specification.
+
`curve`::
    Parameters of a curve, *must* be followed by an identifier, separated by a "`:`" (ex: `curve:1`).

[NOTE]
====
Subplots specifications can be given as "`rows,columns`" or "`id`".
In the latter case, the counting goes from left to right and top to bottom.
The indexes start at *1*.
For curves, it is possible to specify a range of rows and/or columns.
====

=== Figure parameters

`maintitle` | [underline]#Default#: _none_::
    Title of the figure.
`geometry` | [underline]#Default#: _automatic_::
    Geometry of the figure, as "`width, height`". +
    The geometry can be defined as proportional to the number of columns/rows, by adding `*` or `+`. +
+
====
`16*,8` means that the width is "`16 times the number of subplots on a single row`".
====
+
`subplots` | [underline]#Default#: `1,`::
    Enables multiple plots to be included as '`rows, columns`'.
    A single value corresponds to the number of _rows_.
`mergeaxes` | [underline]#Default#: _none_::
    Merge axes of subplots.  +
    **Accepted values**: `X`, `Y`, `Both`, `None`
`ImageFile` | [underline]#Default#: _none_::
    Name of the file where the figure will be saved. +
+
--
WARNING: The file extension must be supported by *Matplotlib*.
    Name of the file where the figure will be saved. +
--
+
`ShowFigure` | [underline]#Default#: `True`::
    Show final figures in a separate window.

=== Layout parameters

`title` | [underline]#Default#: _none_::
    Title of the spectrum.
`xleft` | [underline]#Alt.#: `xmin` | [underline]#Default#: _automatic_::
    Left bound of the X axis.
    `xmin` can be used instead but is misleading if a decreasing X axis is desired.
`xright` | [underline]#Alt.#: `xmax` | [underline]#Default#: _automatic_::
    Right bound of the X axis.
    `xmax` can be used instead but is misleading if a decreasing X axis is desired.
`ytop` | [underline]#Alt.#: `ymax` | [underline]#Default#: _automatic_::
    Top bound of the Y axis.
    `ymax` can be used instead but is misleading if a decreasing Y axis is desired.
`ybottom` | [underline]#Alt.#: `ymin` | [underline]#Default#: _automatic_::
    Bottom bound of the Y axis.
    `ymin` can be used instead but is misleading if a decreasing Y axis is desired.
`xscale` | [underline]#Default#: `linear`::
    Scale for the X axis. +
    **Accepted values**: `linear`, `log`, `log2`, `log10`.
`yscale` | [underline]#Default#: `linear`::
    Scale for the Y axis. +
    **Accepted values**: `linear`, `log`, `log2`, `log10`.
`legend` | [underline]#Default#: `auto`::
    Display legend. +
    **Accepted values**: `No`, `auto`, any supported value for the position of the legend in *Matplotlib*.
`legend_cols` | [underline]#Default#: `1`::
    Number of columns to use in the legend.
`xlabel` | [underline]#Default#: _automatic_::
    Label for the X axis.
`ylabel` | [underline]#Default#: _automatic_::
    Label for the Y axis.
`panel` | [underline]#Default#: `top left`::
    Add a panel in the angle of a plot, in the format `text [@ position]`. +
    **Accepted values**: `position` can be a combination of `upper`/`top` or `lower`/`bottom` and `left`, or `right`

=== Curve definition

`file` | [underline]#Mandatory#::
    Name of the file containing the data. +
`spectroscopy` | [underline]#Mandatory#::
    Type of spectroscopy (acronym).
`level` | [underline]#Mandatory#::
    Level of theory. +
    **Accepted values**: `E` (`Ele`, `Electronic`), `H` (`Harm`, `Harmonic`), `A` (`Anh`, `Anharm`, `Anaharmonic`)
`label` | [underline]#Default#: _none_::
    Label to display in the legend.
`color` | [underline]#Default#: _automatic_::
    Color definition (passed directly *Matplotlib*).
`linestyle` | [underline]#Default#: _automatic_::
    Line style (passed directly to *Matplotlib*).
`linewidth` | [underline]#Default#: _automatic_::
    Line width (passed directly to *Matplotlib*).
`xshift` | [underline]#Default#: `0`::
    Shift value applied to the curve along the X axis.
`yshift` | [underline]#Default#: `0`::
    Shift value applied to the curve along the Y axis. +
    `baseline` is accepted to correct a shift of the baseline.
`xscale` | [underline]#Default#: `abs, 1`::
    Scaling factor to be applied to the X axis.
+
--
NOTE: Scaling is done *before* the shift.
It is possible to specify if the scaling is relative (`rel`) or absolute (`abs`).
In the former case, the axis is shifted so the closest value to 0 is set to 0.
The full form is: +
    `xscale = [_abs_, ] _op_` +
`_op_` supports different operations, with the keyword `x` used to refer to the x value (ex: `10^-x`).
`^` can be used for the exponentiation, `log` refers to the decimal logarithm, `ln` to the natural one.
If absent, the variable is appended at the end of the equation, as `x` or `*x`, depending if it ends with an operation symbol or not.

--
+
`yscale` | [underline]#Default#: `rel, 1`::
    Scaling factor to be applied to the Y axis.
+
--
NOTE: Scaling is done *before* the shift.
See `xscale` for details, with the variable `y` used instead of `x`.
The default scaling method is relative (`rel`), with the Y axis shifted toward the origin.

--
+
`normalize` | [underline]#Default#: `no`::
    Normalize the spectrum (`yes`/`no`). +
+
--
CAUTION: Normalization is applied after scaling to properly apply potential transformation (1/y, log(y)...).
--
+
`show` | [underline]#Default#: `yes`::
    Boolean (`yes`/`no`) indicating if a spectrum must be displayed or not.
`broaden` | [underline]#Default#: `no`::
    Boolean (`yes`/`no`) if a broadening must be applied (may not be applied).
`function` | [underline]#Default#: `gaussian`::
    Function to apply for the broadening  (only read if `broaden` is `yes`). +
    **Accepted values**: `Gaussian`, `Lorentzian`.
`HWHM` | [underline]#Default#: `10`::
    Half-width at half-maximum of the broadening function (only read if `broaden` is `yes`).
`Grain` | [underline]#Default#: `4`::
    Distance between two points along X for the discretization of the spectrum (only read if `broaden` is `yes`).
`NewXMin` | [underline]#Default#: _automatic_::
    Lowest value of X in the broadened spectra (only read if `broaden` is `yes`).
`NewXMax` | [underline]#Default#: _automatic_::
    Highest value of X in the broadened spectra (only read if `broaden` is `yes`).
`yaxis` | [underline]#Default#: `1`::
    Y axis of interest if multiple present.
`subplot` | [underline]#Default#: `-,-`::
    Subplot where the curve should be displayed.
    Ranges can be provided with '`-`'. +
+
====
`1,1-3` prints the curve on the first row and the first to third column.
====
+
`outputfile` | [underline]#Default#: _none_::
    The final (shifted, scaled, broadened) spectra will be saved as a CSV file with the name given as value. +
    `{curve}` can be used as a field to be replaced by the curve name given in the section title. +
+
--
NOTE: Generally used for the default value.  For instance `molA_{curve}_IR_L002.csv` will have a different name for each unique curve section.
--


== Examples