= ESTAMPES: A prototypical program for spectral analysis
:email: julien.bloino@sns.it
:revnumber: 0.3.0
:revremark: Introduction
:toc: left
:toclevels: 1
:icons: font
:stem:
:pygments-style: native

:Gaussian: pass:q[G[small]##AUSSIAN##]
:Estampes: pass:q[E[small]##STAMPES##]


== Preamble

"`{Estampes} Experimental Support Toolbox for the Analysis, Modelling, Plotting and Elucidation of Spectra`" is intended as a toolbox to facilitate prototype development and simple data analysis.


== Presentation

{Estampes} is object-oriented and provides several interfacing layers:

*Data parsing*::
    low-level classes to facilitate data extraction, supported by tools for data transformation, conversion
*Chemical objects*::
    higher-level classes gathering data by chemically intuitive objects.
*User interfaces*::
    graphical and textual tools for the data analysis.


== Requirements

* *Python*:
    version 3.5 or later
* *NumPy*:
    tested on version 1.15.
    Not necessary for basic _data parsing_ features.
* *Matplotlib*:
    tested on version 3.02.
    Only necessary for some _user interfaces_.
* *Qt*:
    tested on version 5.11.
    Only necessary for some _user interface_.


== Data parsing


=== Supported file formats

The program currently supports:

* {Gaussian}: formatted checkpoint files (`.fchk`, `.fch`) and output files (`.out`, `.log`).
+
--
NOTE: Due to the inherent modularity of {Gaussian}, the support of {Gaussian} log files is limited and may fail on some versions of {Gaussian}.
--
* CSV, Text file for spectral data.
* XYZ file format.


=== Interfaces

The parsing facilities are available in the *parser* module.
The module provides a high-level class, *`DataFile`*, and 2 basic functions, `build_qlabel` and `parse_qlabel`, which ensure that the quantity identifier (_qlabel_) is correctly formed.

`DataFile`::
    A basic class acting as a wrapper to lower-level format-specific parsing classes.
    It has an internal file extension checker to load the right object.
    It provides the following attributes and methods:
    `get_data`:::
        the main method.
        Takes a list of _labels_ and returns a dictionary with _labels_ as keys and the data as either float, integers, characters or lists of them.
        Properties should be returned in atomic units (except for the masses, in atomic mass units) +
        `None` is returned if the data could not be extracted.
        Raises:
        `TypeError`::::
            Wrong type of data file object
        `ParseKeyError`::::
            Missing required quantity in data block.
        `IndexError`::::
            State definition inconsistent with available data.
        `QuantityError`::::
            Unsupported quantity
    `version`:::
        Should return a tuple with

        * The name of the program used to generate the file or the file type for '`standard`' exchange formats (ex: PDB, XYZ), as a string
        * A dictionary with program/format versions if relevant (`None` otherwise)

Information on the generation of the _qlabel_ and the structure of the data returned by `get_data` can be found link:data_format.html[here].