= ESTAMPES: A prototypical program for spectral analysis
:email: julien.bloino@sns.it
:revnumber: 0.6.1
:revremark: Bump to new version
:toc: left
:toclevels: 1
:icons: font
:stem:
:pygments-style: native

:Gaussian: pass:q[G[small]##AUSSIAN##]
:Estampes: pass:q[E[small]##STAMPES##]


== Preamble

"`{Estampes}: Experimental Support Toolkit for Analysis, Modelling, Processing and Elaboration of Spectra`" is designed as an ensemble of tools to facilitate prototype development and simple data analysis.


== Presentation

{Estampes} is object-oriented and provides several interfacing layers:

*Data parsing*::
    low-level classes to facilitate data extraction, supported by tools for data transformation, conversion
*Chemical objects*::
    higher-level classes gathering data by chemically intuitive objects.
*User interfaces*::
    graphical and textual tools for the data analysis.


== Requirements

* *Python*:
    version 3.8 or later
* *NumPy*:
    tested on version 1.24.
    Not necessary for basic _data parsing_ features.
* *Matplotlib*:
    tested on version 3.6.
    Only necessary for some _user interfaces_.
* *Qt*:
    tested on version 6.6.1.
    Only necessary for some _user interface_.


== Data parsing


=== Supported file formats

The program currently supports:

* {Gaussian}: formatted checkpoint files (`.fchk`, `.fch`) and output files (`.out`, `.log`).
+
--
NOTE: Due to the inherent modularity of {Gaussian}, the support of {Gaussian} log files is limited and may fail on some versions of {Gaussian}.
--
* CSV, Text file for spectral data.
* XYZ file format.


=== Interfaces

The parsing facilities are available in the ``parser`` module.
The module provides a high-level class, [.codecls]##DataFile##, while `base` provides the classes to interact with the parsing facilities, [.codecls]##QLabel## to generate a valid _qlabel_ item to specify the quantity to extract and [.codecls]##QData## to define the storage structure of extracted data.

[TIP]
====
For most usages, developers will only need the [.codecls]##DataFile## and [.codecls]##QLabel## classes to manage data extraction.

[source, subs='macros,attributes,quotes']
----
[.codekey]##from## estampes.base.qlabel [.codekey]##import## [.codecls]##QLabel##
[.codekey]##from## estampes.parser [.codekey]##import## [.codecls]##DataFile##
----
====

`DataFile`::
    A basic class acting as a wrapper to lower-level format-specific parsing classes.
    It has an internal file extension checker to load the right object.
    It provides the following attributes and methods:
    `get_data`:::
        the main method.
        Takes a list of _labels_ and returns a dictionary with _labels_ as keys and the data as either float, integers, characters or lists of them.
        Properties should be returned in atomic units (except for the masses, in atomic mass units) +
        `None` is returned if the data could not be extracted.
        Raises:
        `TypeError`::::
            Wrong type of data file object
        `ParseKeyError`::::
            Missing required quantity in data block.
        `IndexError`::::
            State definition inconsistent with available data.
        `QuantityError`::::
            Unsupported quantity
    `version`:::
        Should return a tuple with

        * The name of the program used to generate the file or the file type for '`standard`' exchange formats (ex: PDB, XYZ), as a string
        * A dictionary with program/format versions if relevant (`None` otherwise)

Information on the generation of the _qlabel_ and the structure of the data returned by `get_data` can be found link:data_format.html[here].
